// Minimal HTML shell for dynamic pages rendered by the worker (download, account). Same palette as the site.
export const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

export function shell({ lang = 'en', title, body, noindex = true }) {
  const base = lang === 'es' ? '/es' : '';
  const nav = lang === 'es' ? { store: 'Tienda', account: 'Mi cuenta' } : { store: 'Store', account: 'My account' };
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${noindex ? '<meta name="robots" content="noindex,nofollow">' : ''}<title>${esc(title)} · IceMan Studio</title><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet">
<style>body{margin:0;background:#131313;color:#F8FAFC;font-family:Inter,Segoe UI,Arial,sans-serif;line-height:1.55}.wrap{max-width:760px;margin:0 auto;padding:24px 20px 60px}header{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:32px;flex-wrap:wrap}header img{height:40px}header nav a{color:#FFB199;text-decoration:none;font-size:14px;margin-left:16px}h1{font-size:30px;margin:0 0 8px;font-weight:900}h2{font-size:20px;margin:0 0 12px}.lead{color:#9AA3AD;font-size:17px;margin:0 0 22px}.card{background:#181818;border:1px solid #2a2a2a;border-radius:6px;padding:20px 22px;margin-bottom:16px}ul{list-style:none;padding:0;margin:0;display:grid;gap:10px}li{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.btn{display:inline-block;background:#FF7A59;color:#0e0e0e;font-weight:700;padding:10px 16px;border-radius:6px;text-decoration:none;border:0;cursor:pointer;font-size:14px;font-family:inherit;transition:transform 120ms cubic-bezier(.34,1.56,.64,1)}.btn:hover{background:#FFB199}.btn:active{transform:scale(.94)}.btn.ghost{background:transparent;color:#F8FAFC;border:1px solid #2a2a2a}.btn.danger{background:transparent;color:#FFB199;border:1px solid #2a2a2a}.muted{color:#9AA3AD;font-size:14px}form{display:grid;gap:12px;max-width:520px}label{display:grid;gap:6px;font-size:14px;color:#9AA3AD}input{background:#1b1b1b;border:1px solid #2a2a2a;color:#F8FAFC;padding:11px 12px;border-radius:6px;font-size:15px;font-family:inherit}input:focus{outline:none;border-color:#FF7A59}.ok{border-color:#2DD4BF}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.tag{display:inline-block;font-size:12px;border:1px solid #2a2a2a;padding:2px 8px;border-radius:999px;color:#FFB199}small{color:#9AA3AD}</style></head>
<body><div class="wrap"><header><a href="${base}/"><img src="/brand/logo-header.svg" alt="IceMan Studio"></a><nav><a href="${base}/assets/">${nav.store}</a><a href="${base}/account/">${nav.account}</a></nav></header>${body}</div></body></html>`;
}
